import { useState } from "react";
import { Link } from "react-router-dom";
import { Pagination } from "../../../components/Pagination";
import { StatusBadge } from "../../../components/StatusBadge";
import { Table, type Column } from "../../../components/Table";
import { Toolbar } from "../../../components/Toolbar";
import {
  EmptyState,
  ErrorState,
  LoadingState,
} from "../../../components/States";
import { inputStyle } from "../../../components/FormField";
import { useApiList } from "../../../hooks/useApiList";
import type { ComponentAssetRegisterRow } from "../../../types";
import { statusLabel } from "../../../i18n/statusRegistry";
import { t } from '../../../i18n/i18n';

const STATUSES = [
  "",
  "IN_STOCK",
  "INSTALLED",
  "REMOVED",
  "FAILED",
  "UNDER_REPAIR",
  "RECONDITIONED",
  "SCRAPPED",
  "SOLD",
  "RETURNED_TO_VENDOR",
];

/**
 * Inventory → Component Assets: every physical item with resale / asset value and its own identity —
 * assets generated by Goods Receipt (one Asset# per unit received) and physical tires (Serial Number
 * = Asset#). Assets are never created by hand here. Location comes from the backend (warehouse,
 * vehicle registration when installed, none when sold / returned to the vendor).
 */
export function ComponentAssetListPage() {
  const [status, setStatus] = useState("");
  const [kind, setKind] = useState("");
  const [search, setSearch] = useState("");
  const [page, setPage] = useState(1);
  const { data, meta, loading, error } = useApiList<ComponentAssetRegisterRow>(
    "/app/component-assets",
    {
      status: status || undefined,
      kind: kind || undefined,
      search: search || undefined,
      page,
      per_page: 20,
    },
    0,
  );
  const rows = data.map((r) => ({
    ...r,
    id: `${r.kind}-${r.id}`,
    asset_id: r.id,
  }));

  const columns: Column<(typeof rows)[number]>[] = [
    {
      key: "status",
      header: t('common.fields.status'),
      render: (r) => <StatusBadge status={r.status} />,
    },
    {
      key: "identity",
      header: t('tenantComponents.fields.serialsAssetNumber'),
      render: (r) => (
        <Link
          to={
            r.kind === "TIRE"
              ? `/app/tires/${r.asset_id}`
              : `/app/component-assets/${r.asset_id}`
          }
          data-asset-identity
        >
          <span style={{ fontFamily: "monospace", fontWeight: 600 }}>
            {r.asset_number ?? r.serial_number ?? "—"}
          </span>
          {r.kind === "TIRE" ? (
            <span style={{ display: "block", fontSize: 11, color: "#6b7280" }}>
              {t('tenantComponents.actions.tireSerialNumberAssetNumber')}
            </span>
          ) : r.serial_number ? (
            <span style={{ display: "block", fontSize: 11, color: "#6b7280" }}>
              S/N {r.serial_number}
            </span>
          ) : null}
        </Link>
      ),
    },
    {
      key: "group",
      header: t('common.fields.componentGroup'),
      render: (r) => r.component_group ?? "—",
    },
    { key: "product", header: t('common.fields.product'), render: (r) => r.product_name ?? "—" },
    {
      key: "location",
      header: t('tenantComponents.fields.locationVehicle'),
      render: (r) =>
        !r.location ? (
          "—"
        ) : r.location.type === "VEHICLE" ? (
          <Link to={`/app/vehicles/${r.location.id}`}>
            {r.location.label ?? "—"}
          </Link>
        ) : (
          <span>{r.location.label ?? "—"}</span>
        ),
    },
  ];

  const reset = () => setPage(1);

  return (
    <div>
      <h1 style={{ fontSize: 22, marginBottom: 6 }}>{t('tenantComponents.titles.componentAssets')}</h1>
      <p style={{ marginTop: 0, fontSize: 13, color: "#6b7280" }}>
        {t('tenantComponents.help.physicalItemsTrackedIndividuallyAssetNumber')}
      </p>
      <div
        style={{ display: "flex", gap: 4, marginBottom: 14, flexWrap: "wrap" }}
      >
        {STATUSES.map((s) => (
          <button
            key={s}
            onClick={() => {
              setStatus(s);
              reset();
            }}
            className={status === s ? "btn-primary" : "btn-secondary"}
            style={{ padding: "4px 10px", fontSize: 11 }}
          >
            {s ? statusLabel(s) : t('common.actions.all')}
          </button>
        ))}
      </div>
      <Toolbar
        search={search}
        onSearchChange={(v) => {
          setSearch(v);
          reset();
        }}
        actions={
          <select
            aria-label={t('tenantComponents.fields.assetType')}
            value={kind}
            onChange={(e) => {
              setKind(e.target.value);
              reset();
            }}
            style={{ ...inputStyle, width: 160 }}
          >
            <option value="">{t('tenantComponents.filters.allAssets')}</option>
            <option value="COMPONENT">{t('tenantComponents.fields.components')}</option>
            <option value="TIRE">{t('tenantComponents.fields.tires')}</option>
          </select>
        }
      />
      {error && <ErrorState message={error} />}
      {!error && loading && rows.length === 0 && <LoadingState />}
      {!error && !loading && rows.length === 0 && (
        <EmptyState label={t('tenantComponents.empty.noComponentAssetsFound')} />
      )}
      {!error && rows.length > 0 && (
        <div style={{ overflowX: "auto" }} data-component-asset-list>
          <Table columns={columns} rows={rows} />
        </div>
      )}
      {meta && meta.last_page > 1 && (
        <Pagination meta={meta} onPageChange={setPage} />
      )}
    </div>
  );
}
