<?php

namespace Tests\Feature;

use App\Domain\ComponentAsset\Models\ComponentAsset;
use App\Domain\ComponentAsset\Services\ComponentAssetRegisterService;
use App\Domain\Procurement\Models\GoodsReceiptItem;
use App\Domain\Procurement\Models\PurchaseOrder;
use App\Domain\Procurement\Models\PurchaseOrderItem;
use App\Domain\ProductMaster\Models\Product;
use App\Domain\Tire\Models\Tire;
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Tests\TestCase;

/**
 * Inventory → Component Assets: physical assets generated by Goods Receipt (one per unit actually
 * received of a serial-tracked, non-tire product; idempotent), tires listed with Serial Number as
 * Asset#, location derived from the current relations, Return to Vendor by selected Asset#, and
 * Sell Sparepart marking an asset SOLD.
 */
class ComponentAssetRegisterTest extends TestCase
{
    private const PERMISSIONS = [
        'component_asset.view', 'component_asset.install', 'component_asset.remove', 'component_asset.manage', 'tire.view',
        'purchase_order.view', 'goods_receipt.view', 'goods_receipt.post', 'purchase_return.create', 'purchase_return.decide', 'purchase_return.receive_redelivery',
        'sparepart_sale.view', 'sparepart_sale.create', 'sparepart_sale.approve',
    ];

    private function scenario(int $ordered = 10, array $productOverrides = []): array
    {
        $tenant = $this->makeTenant(['code' => 'CAR-'.Str::random(4)]);
        foreach (['VEHICLE', 'INVENTORY', 'PROCUREMENT', 'PARTNER', 'COMPONENT', 'TIRE'] as $module) {
            $this->grantModule($tenant, $module);
        }
        $branch = $this->makeBranch($tenant);
        $warehouse = $this->makeWarehouse($tenant, $branch);
        $vehicle = $this->makeVehicle($tenant, $branch, $this->makeVehicleCategory(), ['registration_number' => 'B 9 CAR']);
        $group = $this->makeComponentGroup();
        $product = $this->makeProduct($tenant, null, null, $productOverrides + ['name' => 'Alternator 24V', 'product_type' => 'SPARE_PART', 'track_serial_number' => true]);
        DB::table('product_component_groups')->insert(['product_id' => $product->id, 'component_group_id' => $group->id, 'created_at' => now(), 'updated_at' => now()]);
        $po = PurchaseOrder::query()->create([
            'tenant_id' => $tenant->id, 'po_number' => 'PO/CA/'.Str::random(6), 'partner_id' => $this->makePartner($tenant)->id, 'delivery_warehouse_id' => $warehouse->id,
            'status' => 'ISSUED', 'order_date' => '2026-10-01', 'subtotal' => $ordered * 1500000, 'tax_total' => 0, 'freight_cost' => 0, 'total' => $ordered * 1500000,
        ]);
        $line = PurchaseOrderItem::query()->create(['purchase_order_id' => $po->id, 'product_id' => $product->id, 'quantity_ordered' => $ordered, 'unit_price' => 1500000, 'line_total' => $ordered * 1500000]);
        [, $token] = $this->makeTenantUser($tenant, self::PERMISSIONS);

        return compact('tenant', 'branch', 'warehouse', 'vehicle', 'group', 'product', 'po', 'line') + ['headers' => $this->authHeaders($token)];
    }

    private function receive(array $s, float $qty, ?string $lineId = null)
    {
        return $this->postJson("/api/v1/app/purchase-orders/{$s['po']->id}/goods-receipts", [
            'lines' => [['purchase_order_item_id' => $lineId ?? $s['line']->id, 'quantity_accepted' => $qty]], 'invoice_mode' => 'NEW',
            'vendor_invoice_number' => 'INV-'.Str::random(6), 'vendor_invoice_date' => '2026-10-02', 'amount' => '1000', 'terms_of_payment_days' => '30',
        ], $s['headers']);
    }

    private function assets(array $s)
    {
        return ComponentAsset::query()->withoutGlobalScopes()->whereNull('deleted_at')->where('tenant_id', $s['tenant']->id)->where('product_id', $s['product']->id)->orderBy('asset_number')->get();
    }

    private function register(array $s, string $query = '')
    {
        return collect($this->getJson('/api/v1/app/component-assets?per_page=100'.$query, $s['headers'])->assertOk()->json('data'));
    }

    public function test_goods_receipt_generates_one_asset_per_unit_actually_received(): void
    {
        $s = $this->scenario(10);
        $this->receive($s, 3)->assertStatus(201);
        $assets = $this->assets($s);
        $this->assertCount(3, $assets, 'received 3 of 10 ordered → 3 assets');
        foreach ($assets as $asset) {
            $this->assertSame(['IN_STOCK', $s['warehouse']->id, '1500000.0000', $s['group']->id], [$asset->current_status, $asset->current_warehouse_id, $asset->purchase_cost, $asset->component_group_id]);
            $this->assertMatchesRegularExpression('/^AST-\d{4}-\d{6}$/', $asset->asset_number);
        }
        $this->assertSame([1, 2, 3], $assets->pluck('receipt_sequence')->sort()->values()->all());

        // Partial receipts add up: 3 + 2 = 5, every Asset# unique.
        $this->receive($s, 2)->assertStatus(201);
        $assets = $this->assets($s);
        $this->assertCount(5, $assets);
        $this->assertCount(5, $assets->pluck('asset_number')->unique());

        // Retrying generation for an already-processed receipt line generates nothing more.
        $register = app(ComponentAssetRegisterService::class);
        foreach (GoodsReceiptItem::query()->where('purchase_order_item_id', $s['line']->id)->get() as $receiptLine) {
            $this->assertSame([], DB::transaction(fn () => $register->generateFromReceipt($receiptLine, $s['product'], $s['tenant']->id, $s['warehouse']->id, null)));
        }
        $this->assertCount(5, $this->assets($s));
        // And the database refuses a duplicate unit of the same receipt line.
        $this->expectException(QueryException::class);
        ComponentAsset::query()->create(['tenant_id' => $s['tenant']->id, 'product_id' => $s['product']->id, 'asset_number' => 'AST-DUP', 'current_status' => 'IN_STOCK',
            'current_warehouse_id' => $s['warehouse']->id, 'goods_receipt_item_id' => $assets[0]->goods_receipt_item_id, 'receipt_sequence' => $assets[0]->receipt_sequence]);
    }

    public function test_untracked_consumable_and_tire_products_generate_no_component_assets(): void
    {
        foreach ([['track_serial_number' => false], ['product_type' => 'CONSUMABLE'], ['product_type' => 'TIRE']] as $overrides) {
            $s = $this->scenario(5, $overrides);
            $this->receive($s, 2)->assertStatus(201);
            $this->assertCount(0, $this->assets($s), json_encode($overrides));
        }
        // A serial-tracked product is received in whole units.
        $s = $this->scenario(5);
        $this->receive($s, 1.5)->assertStatus(422);
        $this->assertCount(0, $this->assets($s));
    }

    public function test_asset_number_is_unique_per_tenant(): void
    {
        $s = $this->scenario();
        ComponentAsset::query()->create(['tenant_id' => $s['tenant']->id, 'asset_number' => 'AST-X', 'current_status' => 'IN_STOCK', 'current_warehouse_id' => $s['warehouse']->id]);
        $other = $this->scenario();
        ComponentAsset::query()->create(['tenant_id' => $other['tenant']->id, 'asset_number' => 'AST-X', 'current_status' => 'IN_STOCK', 'current_warehouse_id' => $other['warehouse']->id]);
        $this->expectException(QueryException::class);
        ComponentAsset::query()->create(['tenant_id' => $s['tenant']->id, 'asset_number' => 'AST-X', 'current_status' => 'IN_STOCK', 'current_warehouse_id' => $s['warehouse']->id]);
    }

    public function test_register_lists_tires_with_serial_as_asset_number_and_derives_the_location(): void
    {
        $s = $this->scenario();
        $this->receive($s, 3)->assertStatus(201);
        [$inStock, $installed, $removed] = $this->assets($s)->all();
        $this->postJson("/api/v1/app/component-assets/{$installed->id}/install", ['vehicle_id' => $s['vehicle']->id], $s['headers'])->assertStatus(201);
        $this->postJson("/api/v1/app/component-assets/{$removed->id}/install", ['vehicle_id' => $s['vehicle']->id], $s['headers'])->assertStatus(201);
        $this->postJson("/api/v1/app/component-assets/{$removed->id}/remove", ['removal_reason' => 'Noise', 'disposition' => 'REUSE', 'warehouse_id' => $s['warehouse']->id], $s['headers'])->assertStatus(201);

        $tireProduct = $this->makeProduct($s['tenant'], null, null, ['product_type' => 'TIRE', 'name' => 'Highway Rib']);
        $tire = Tire::query()->create(['tenant_id' => $s['tenant']->id, 'product_id' => $tireProduct->id, 'serial_number' => 'TIRE-ASSET-01', 'current_status' => 'IN_STOCK', 'current_warehouse_id' => $s['warehouse']->id]);

        $rows = $this->register($s)->keyBy('asset_number');
        $this->assertSame(['COMPONENT', 'IN_STOCK', 'WAREHOUSE', $s['warehouse']->name, 'Alternator 24V', $s['group']->name], [
            $rows[$inStock->asset_number]['kind'], $rows[$inStock->asset_number]['status'], $rows[$inStock->asset_number]['location']['type'],
            $rows[$inStock->asset_number]['location']['label'], $rows[$inStock->asset_number]['product_name'], $rows[$inStock->asset_number]['component_group'],
        ]);
        $this->assertSame(['INSTALLED', 'VEHICLE', 'B 9 CAR'], [$rows[$installed->asset_number]['status'], $rows[$installed->asset_number]['location']['type'], $rows[$installed->asset_number]['location']['label']]);
        $this->assertSame(['REMOVED', 'WAREHOUSE'], [$rows[$removed->asset_number]['status'], $rows[$removed->asset_number]['location']['type']]);
        // The tire is the same physical record as the tire list: Asset# = Serial Number.
        $this->assertSame(['TIRE', $tire->id, 'TIRE-ASSET-01', 'TIRE-ASSET-01', 'WAREHOUSE'], [
            $rows['TIRE-ASSET-01']['kind'], $rows['TIRE-ASSET-01']['id'], $rows['TIRE-ASSET-01']['serial_number'], $rows['TIRE-ASSET-01']['asset_number'], $rows['TIRE-ASSET-01']['location']['type'],
        ]);
        $this->assertContains($tire->id, collect($this->getJson('/api/v1/app/tires?per_page=100', $s['headers'])->json('data'))->pluck('id'));

        // Filters: status, kind, search.
        $this->assertSame(['INSTALLED'], $this->register($s, '&status=INSTALLED')->pluck('status')->unique()->values()->all());
        $this->assertSame(['TIRE'], $this->register($s, '&kind=TIRE')->pluck('kind')->unique()->values()->all());
        $this->assertSame(['TIRE-ASSET-01'], $this->register($s, '&search=ASSET-01')->pluck('asset_number')->all());

        // Without tire.view the tires are not listed.
        [, $token] = $this->makeTenantUser($s['tenant'], ['component_asset.view']);
        $kinds = collect($this->getJson('/api/v1/app/component-assets?per_page=100', $this->authHeaders($token))->assertOk()->json('data'))->pluck('kind')->unique()->values()->all();
        $this->assertSame(['COMPONENT'], $kinds);
    }

    public function test_status_location_invariants_are_enforced_by_the_database(): void
    {
        $s = $this->scenario();
        $this->receive($s, 1)->assertStatus(201);
        $asset = $this->assets($s)->first();
        foreach ([
            ['current_status' => 'INSTALLED', 'current_warehouse_id' => null],
            ['current_status' => 'SOLD'],
            ['current_status' => 'IN_STOCK', 'current_warehouse_id' => null],
        ] as $invalid) {
            try {
                DB::transaction(fn () => DB::table('component_assets')->where('id', $asset->id)->update($invalid));
                $this->fail('accepted '.json_encode($invalid));
            } catch (QueryException $e) {
                $this->assertStringContainsString('component_assets_location_check', $e->getMessage());
            }
        }
    }

    public function test_selling_a_removed_asset_marks_it_sold_without_location_and_keeps_history(): void
    {
        $s = $this->scenario();
        $this->receive($s, 2)->assertStatus(201);
        [$asset, $inStock] = $this->assets($s)->all();
        $this->postJson("/api/v1/app/component-assets/{$asset->id}/install", ['vehicle_id' => $s['vehicle']->id], $s['headers'])->assertStatus(201);
        $this->postJson("/api/v1/app/component-assets/{$asset->id}/remove", ['removal_reason' => 'Worn', 'disposition' => 'REUSE', 'warehouse_id' => $s['warehouse']->id], $s['headers'])->assertStatus(201);

        $sell = fn (array $ids, string $type = 'OPERATIONAL_REUSE') => $this->postJson('/api/v1/app/sparepart-sales/component-assets', [
            'component_asset_ids' => $ids, 'sale_type' => $type, 'buyer_type' => 'EXTERNAL', 'buyer_name' => 'CV Bekas Jaya', 'unit_price' => '450000.50',
        ], $s['headers']);
        $sell([$inStock->id])->assertStatus(422); // an IN_STOCK asset is not for sale
        $sale = $sell([$asset->id])->assertStatus(201)->json('data.0');
        $this->assertSame(['COMPONENT_ASSET', $asset->asset_number, '1.0000', 'DRAFT'], [$sale['source_type'], $sale['asset_number'], $sale['quantity'], $sale['status']]);
        $sell([$asset->id])->assertStatus(422); // already in an active sale
        $this->postJson("/api/v1/app/component-assets/{$asset->id}/install", ['vehicle_id' => $s['vehicle']->id], $s['headers'])->assertStatus(422);

        $this->postJson("/api/v1/app/sparepart-sales/{$sale['id']}/submit", [], $s['headers'])->assertOk();
        [, $approver] = $this->makeTenantUser($s['tenant'], ['sparepart_sale.view', 'sparepart_sale.approve']);
        $this->postJson("/api/v1/app/sparepart-sales/{$sale['id']}/decide", ['decision' => 'APPROVE'], $this->authHeaders($approver))->assertOk();

        $sold = $asset->fresh();
        $this->assertSame(['SOLD', null, null, $sale['id']], [$sold->current_status, $sold->current_vehicle_id, $sold->current_warehouse_id, $sold->spare_part_sale_id]);
        $this->assertNotNull($sold->sold_at);
        $detail = $this->getJson("/api/v1/app/component-assets/{$asset->id}", $s['headers'])->assertOk()->json('data');
        $this->assertNull($detail['location']);
        $this->assertCount(1, $detail['installations'], 'installation history kept');
        $this->assertCount(1, $detail['removals']);
        $this->assertSame('SOLD', collect($detail['status_history'])->last()['to']);
        $this->assertSame('—', $this->register($s)->firstWhere('id', $asset->id)['location'] ?? '—');
        // A scrapped asset is only sold as scrap material.
        $this->postJson("/api/v1/app/component-assets/{$inStock->id}/install", ['vehicle_id' => $s['vehicle']->id], $s['headers'])->assertStatus(201);
        $this->postJson("/api/v1/app/component-assets/{$inStock->id}/remove", ['removal_reason' => 'Burnt', 'disposition' => 'SCRAP', 'warehouse_id' => $s['warehouse']->id], $s['headers'])->assertStatus(201);
        $sell([$inStock->id])->assertStatus(422);
        $sell([$inStock->id], 'SCRAP_MATERIAL')->assertStatus(201);
    }

    public function test_status_history_keeps_transition_order_when_changes_share_a_second(): void
    {
        $s = $this->scenario();
        $this->receive($s, 1)->assertStatus(201);
        $asset = $this->assets($s)->first();
        DB::table('audit_logs')->where('resource_type', 'ComponentAsset')->where('resource_id', $asset->id)->delete();
        // Written newest first, all within the same second (audit_logs.created_at has second precision).
        $at = '2026-10-01 10:00:00';
        foreach ([['REMOVED', 'SOLD'], ['INSTALLED', 'REMOVED'], ['IN_STOCK', 'INSTALLED']] as [$from, $to]) {
            DB::table('audit_logs')->insert(['id' => (string) Str::uuid(), 'tenant_id' => $s['tenant']->id, 'resource_type' => 'ComponentAsset',
                'resource_id' => $asset->id, 'action' => 'updated', 'old_values' => json_encode(['current_status' => $from]),
                'new_values' => json_encode(['current_status' => $to]), 'created_at' => $at]);
        }
        DB::table('audit_logs')->insert(['id' => (string) Str::uuid(), 'tenant_id' => $s['tenant']->id, 'resource_type' => 'ComponentAsset',
            'resource_id' => $asset->id, 'action' => 'created', 'old_values' => null,
            'new_values' => json_encode(['current_status' => 'IN_STOCK']), 'created_at' => $at]);

        $history = $this->getJson("/api/v1/app/component-assets/{$asset->id}", $s['headers'])->assertOk()->json('data.status_history');
        $this->assertSame(['IN_STOCK', 'INSTALLED', 'REMOVED', 'SOLD'], array_column($history, 'to'));
        $this->assertSame('created', $history[0]['action']);
    }

    public function test_return_to_vendor_takes_the_selected_asset_numbers_and_redelivery_adds_new_units(): void
    {
        $s = $this->scenario(10);
        $this->receive($s, 3)->assertStatus(201);
        [$a, $b, $c] = $this->assets($s)->all();
        $summary = $this->getJson("/api/v1/app/purchase-orders/{$s['po']->id}", $s['headers'])->assertOk()->json("data.return_summary.items.{$s['line']->id}.returnable_assets");
        $this->assertEqualsCanonicalizing([$a->asset_number, $b->asset_number, $c->asset_number], array_column($summary, 'asset_number'));

        $return = fn (array $ids, float $qty = 1) => $this->postJson("/api/v1/app/purchase-orders/{$s['po']->id}/returns", [
            'return_option' => 'REDELIVERY', 'items' => [['purchase_order_item_id' => $s['line']->id, 'quantity' => $qty, 'component_asset_ids' => $ids]],
        ], $s['headers']);
        $return([])->assertStatus(422);                     // selection required
        $return([$a->id, $b->id])->assertStatus(422);       // must match the quantity
        $this->postJson("/api/v1/app/component-assets/{$c->id}/install", ['vehicle_id' => $s['vehicle']->id], $s['headers'])->assertStatus(201);
        $return([$c->id])->assertStatus(422);               // installed: not in stock
        $this->assertSame('IN_STOCK', $a->fresh()->current_status, 'nothing changed by refused returns');

        $returnId = $return([$a->id])->assertStatus(201)->json('data.id');
        $returned = $a->fresh();
        $this->assertSame(['RETURNED_TO_VENDOR', null, $returnId], [$returned->current_status, $returned->current_warehouse_id, $returned->purchase_return_id]);
        $this->assertNull($this->register($s)->firstWhere('id', $a->id)['location']);

        // The redelivered unit is a new physical item: its Goods Receipt generates one new asset.
        $this->get("/api/v1/app/purchase-returns/{$returnId}/print", $s['headers'])->assertOk();
        $this->postJson("/api/v1/app/purchase-returns/{$returnId}/receive-redelivery", [], $s['headers'])->assertOk();
        $this->receive($s, 1)->assertStatus(201);
        $assets = $this->assets($s);
        $this->assertCount(4, $assets);
        $this->assertSame(1, $assets->where('current_status', 'RETURNED_TO_VENDOR')->count());
        $this->assertSame(2, $assets->where('current_status', 'IN_STOCK')->count());
    }

    public function test_manual_creation_is_retired_and_access_is_permission_and_tenant_scoped(): void
    {
        $s = $this->scenario();
        $this->postJson('/api/v1/app/component-assets', ['serial_number' => 'X-1'], $s['headers'])->assertStatus(410);
        $this->assertSame(0, ComponentAsset::query()->where('serial_number', 'X-1')->count());

        [, $noView] = $this->makeTenantUser($s['tenant'], ['tire.view']);
        $this->getJson('/api/v1/app/component-assets', $this->authHeaders($noView))->assertStatus(403);

        $this->receive($s, 1)->assertStatus(201);
        $other = $this->scenario();
        $this->assertSame(0, $this->register($other)->where('kind', 'COMPONENT')->count(), 'another tenant sees none of these assets');
        $this->getJson('/api/v1/app/component-assets/'.$this->assets($s)->first()->id, $other['headers'])->assertStatus(404);
        $this->assertInstanceOf(Product::class, $s['product']);
    }
}
